"$schema" = "https://starship.rs/config-schema.json"

add_newline = true

format = """
[░▒▓](#1d2230)\
$os\
$time\
[](fg:#1d2230 bg:#394260)\
$username\
$shell\
$shlvl\
$sudo\
[](fg:#394260 bg:#212736)\
$git_branch\
$git_status\
$package\
$docker_context\
$python\
$golang\
$rust\
$nodejs\
$php\
$java\
$c\
$cpp\
$lua\
[](fg:#212736 bg:#769ff0)\
$directory\
[](fg:#769ff0)\
\n$character
"""

right_format = "$cmd_duration"

# =========================================================
# CHARACTER
# =========================================================

[character]
success_symbol = "[❯](bold fg:#769ff0)"
error_symbol = "[❯](bold fg:#e06c75)"
vimcmd_symbol = "[❮](bold fg:#a0a9cb)"

# =========================================================
# OS
# =========================================================

[os]
disabled = false
style = "fg:#090c0c bg:#1d2230"
format = "[ $symbol ]($style)"

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
RockyLinux = " "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

# =========================================================
# TIME
# =========================================================

[time]
disabled = false
time_format = "%R"

style = "fg:#a0a9cb bg:#1d2230"

format = "[ $time ]($style)"

# =========================================================
# USER
# =========================================================

[username]
disabled = false
show_always = true

style_user = "fg:#769ff0 bg:#394260"
style_root = "fg:#e06c75 bg:#394260"

format = "[  $user ]($style)"

# =========================================================
# SHELL
# =========================================================

[shell]
disabled = false

bash_indicator = " bash"
fish_indicator = "󰈺 fish"
zsh_indicator = " zsh"

style = "fg:#769ff0 bg:#394260"

format = "[ $indicator ]($style)"

# =========================================================
# SHLVL
# =========================================================

[shlvl]
disabled = false
threshold = 2

symbol = ""

style = "fg:#769ff0 bg:#394260"

format = "[ $symbol $shlvl ]($style)"

# =========================================================
# SUDO
# =========================================================

[sudo]
disabled = false

symbol = "󰌆"

style = "fg:#e06c75 bg:#394260"

format = "[ $symbol ]($style)"

# =========================================================
# GIT
# =========================================================

[git_branch]
symbol = ""

style = "fg:#769ff0 bg:#212736"

format = "[ $symbol $branch ]($style)"

[git_status]
style = "fg:#769ff0 bg:#212736"

format = "[ $all_status$ahead_behind ]($style)"

# =========================================================
# PACKAGE
# =========================================================

[package]
symbol = ""

style = "fg:#769ff0 bg:#212736"

format = "[ $symbol $version ]($style)"

# =========================================================
# LANGUAGES
# =========================================================

[python]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = "[ $symbol $version ]($style)"

[golang]
symbol = "󰟓"
style = "fg:#769ff0 bg:#212736"
format = "[ $symbol $version ]($style)"

[rust]
symbol = "󱘗"
style = "fg:#769ff0 bg:#212736"
format = "[ $symbol $version ]($style)"

[nodejs]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = "[ $symbol $version ]($style)"

[php]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = "[ $symbol $version ]($style)"

[java]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = "[ $symbol $version ]($style)"

[c]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = "[ $symbol $version ]($style)"

[cpp]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = "[ $symbol $version ]($style)"

[lua]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = "[ $symbol $version ]($style)"

[docker_context]
symbol = ""
style = "fg:#769ff0 bg:#212736"
format = "[ $symbol ]($style)"

# =========================================================
# DIRECTORY
# =========================================================

[directory]
style = "fg:#090c0c bg:#769ff0"

format = "[ $path ]($style)"

truncation_length = 6
truncation_symbol = "••/"

home_symbol = ""

[directory.substitutions]
Documents = "󰈙"
Downloads = ""
Music = ""
Pictures = ""

# =========================================================
# CMD DURATION
# =========================================================

[cmd_duration]
min_time = 2000

style = "fg:#a0a9cb"

format = "[took $duration]($style)"
